classDiagram
    class Library {
      +add_book()
      +register_user()
      +create_loan()
    }
    class User{
      +name:str
      +email:str
    }
    class Book{
      +title:string
      +author:string
      +state:bool
      +mark_as_unavailable()
      +mark_as_available()
    }
    class Loan {
        +start_date:str
        +end_date:str
        +close_loan()
    }